version: '3.0'

expectations:
  population_size: 10000

actions:

  generate_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/input.feather

  generate_report:
    run: cohort-report:v3.0.0 output/input.feather
    needs: [generate_cohort]
    config:
      output_path: output/cohort_reports_outputs
    outputs:
      moderately_sensitive:
        reports: output/cohort_reports_outputs/descriptives_input.html
        reports: output/cohort_reports_outputs/*.png
      

  counts:
    run: python:latest python analysis/counts.py
    needs: [generate_cohort]
    outputs:
      moderately_sensitive: 
        tabdata: output/tabledata.csv
        cohort_2: output/codecounts_week.csv
        
  freq_plots:
    run: python:latest python analysis/freq_plot.py
    needs: [counts]
    outputs:
      moderately_sensitive:  
        plots: output/plots.svg
#        figs: output/figs.svg

  km_plots:
    run: python:latest python analysis/km_plot.py
    needs: [generate_cohort]
    outputs:
      moderately_sensitive:  
        figs: output/figs.svg

  notebook_md:
    run: jupyter:latest jupyter nbconvert /workspace/notebooks/primary-care-covid-codes.ipynb --execute --to html --template basic --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400 --no-input
    needs: [generate_cohort,km_plots,counts]
    outputs:
      moderately_sensitive:
        md: output/primary-care-covid-codes.html
