version: '3.0'

expectations:
  population_size: 10000

actions:

  generate_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/input.feather

  counts:
    run: python:latest python analysis/counts.py
    needs: [generate_cohort]
    outputs:
      moderately_sensitive: 
        cohort_2: output/caseness/codecounts_week.csv

  freq_plots:
    run: python:latest python analysis/freq_plot.py
    needs: [counts]
    outputs:
      moderately_sensitive:  
        plots: output/caseness/plots.svg